config/routes.rb
ChoreTracker::Application.routes.draw do
  # Generated routes for models
  resources :chores
  resources :tasks
  resources :children
  
  # Setting default route
  root to: 'chores#index'
  

end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chore }
      else
        format.html { render action: 'new' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:child_id, :task_id, :due_on, :completed)
    end
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :due_on %><br />
    <%= f.date_select :due_on %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h2>Listing chores</h2>

<table>
  <tr>
    <th width="125" align="left">Child</th>
    <th width="200" align="left">Task</th>
    <th width="75">Due on</th>
    <th width="125">Completed</th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.child_id %></td>
    <td><%= chore.task_id %></td>
    <td align="center"><%= chore.due_on %></td>
    <td align="center"><%= chore.completed %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child:</b>
  <%= @chore.child_id %>
</p>

<p>
  <b>Task:</b>
  <%= @chore.task_id %>
</p>

<p>
  <b>Due on:</b>
  <%= @chore.due_on %>
</p>

<p>
  <b>Completed:</b>
  <%= @chore.completed %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>